### ISSUE TITLE
Not work after restart Xcode

### ISSUE THREAD

**Issue by NSDeveloper** [Johnykutty/JKBlockCommenter#3]
In Xcode6.2,it doesn't  work after restart,I need reinstall to make it work.

**Comment by Johnykutty** [comment]
Reinstall plugin?. It may due to lack of PlugIn Compatibility UUIDs of Xcode 6.2 in your installed plugin. I've added latest DVTPlugInCompatibilityUUIDs to the info plist as of Alcatraz.
