### ISSUE TITLE
Swift 2

### ISSUE THREAD

**Issue by WE-St0r** [Johnykutty/JKBlockCommenter#4]
In swift Apple changes comment syntax. Unfortunately JKBlockCommenter generates docs in swift 1.2 syntax. Could you add support for swift 2?

thanks in advance

**Comment by Johnykutty** [comment]
Actually this plugin is not meant for creating documentation comment, just comment a portion of code that a developer thinks that is not needed temporarily or uncomment them with only few keystrokes.

If you need documentation comments, you can use https://github.com/onevcat/VVDocumenter-Xcode for this purpose.

Hpe this make sense
